/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinestraAggiungiFascicoloClienteEsistente.java
 *
 * Created on 25-gen-2012, 12.57.46
 */

package gestionale.view;

import gestionale.Constants;
import gestionale.control.AzioneNuovoFascicoloClienteEsistente;
import gestionale.model.ClienteAstratto;

/**
 *
 * @author nicolafelicecapece
 */
public class FinestraAggiungiFascicoloClienteEsistente extends javax.swing.JDialog {

    private Vista vista;

    /** Creates new form FinestraAggiungiFascicoloClienteEsistente */
    public FinestraAggiungiFascicoloClienteEsistente(Vista vista) {
        this.vista = vista;
        initComponents();
        postInizializza();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlClienteSelezionato = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txNotReato = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txRGNR = new javax.swing.JTextField();
        txRGGIP = new javax.swing.JTextField();
        txNumSentenza = new javax.swing.JTextField();
        jAsteriscoNotReato = new javax.swing.JLabel();
        jAsteriscoRGNR = new javax.swing.JLabel();
        jAsteriscoRGGIP = new javax.swing.JLabel();
        jAsteriscoNumSent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlClienteSelezionato.setText("jLabel12");

        jLabel8.setText("Notizia di reato");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("RGNR");

        jLabel10.setText("RG-GIP");

        jLabel11.setText("Numero Sentenza");

        jAsteriscoNotReato.setBackground(new java.awt.Color(255, 0, 0));
        jAsteriscoNotReato.setForeground(new java.awt.Color(255, 0, 0));
        jAsteriscoNotReato.setText("*");

        jAsteriscoRGNR.setForeground(new java.awt.Color(255, 0, 0));
        jAsteriscoRGNR.setText("*");

        jAsteriscoRGGIP.setForeground(new java.awt.Color(255, 0, 0));
        jAsteriscoRGGIP.setText("*");

        jAsteriscoNumSent.setForeground(new java.awt.Color(255, 0, 0));
        jAsteriscoNumSent.setText("*");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(332, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 164, Short.MAX_VALUE)
                                .add(jButton2))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel8)
                                    .add(jLabel11)
                                    .add(jLabel10)
                                    .add(jLabel9))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jAsteriscoNotReato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jAsteriscoRGNR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jAsteriscoRGGIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jAsteriscoNumSent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txNumSentenza)
                                    .add(txRGGIP)
                                    .add(txRGNR)
                                    .add(txNotReato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jlClienteSelezionato)
                        .addContainerGap(324, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jlClienteSelezionato)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txNotReato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jAsteriscoNotReato))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txRGNR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jAsteriscoRGNR)
                            .add(jLabel9))
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txRGGIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jAsteriscoRGGIP)
                            .add(jLabel10))
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txNumSentenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jAsteriscoNumSent)
                            .add(jLabel11))
                        .add(50, 50, 50)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton2)))
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void postInizializza() {
        this.jLabel1.setVisible(false);
        disabilitaAsterischi();
        ModelloComboBoxAutGiud mcba = new ModelloComboBoxAutGiud();
        this.jComboBox1.setModel(mcba);
        this.jComboBox1.setSelectedIndex(0);
        AzioneNuovoFascicoloClienteEsistente afce = (AzioneNuovoFascicoloClienteEsistente) this.vista.getControllo().getAzione(Constants.AZIONE_NUOVO_FASCICOLO_CLIENTE_ESISTENTE);
        this.jButton2.setAction(afce);
        this.setModal(true);
        this.pack();
    }

    public void riempiNome() {
        ClienteAstratto cliente = (ClienteAstratto) this.vista.getModello().getBean(Constants.CLIENTE);
        this.jlClienteSelezionato.setText("Cliente selezionato: " + cliente.getNome());
    }

    public String restituisciNotiziaReato() {
        return this.txNotReato.getText();
    }

    public String restituisciRGNR() {
        return this.txRGNR.getText();
    }

    public String restituisciRGGIP() {
        return this.txRGGIP.getText();
    }

    public String restituisciNumeroSentenza() {
        return this.txNumSentenza.getText();
    }

    public String restituisciAutGiud() {
        return (String) this.jComboBox1.getSelectedItem();
    }

    public void pulisciCampi() {
        this.txNotReato.setText("");
        this.txNumSentenza.setText("");
        this.txRGGIP.setText("");
        this.txRGNR.setText("");
    }

    public void disabilitaAsterischi() {
        this.jAsteriscoNotReato.setVisible(false);
        this.jAsteriscoRGNR.setVisible(false);
        this.jAsteriscoRGGIP.setVisible(false);
        this.jAsteriscoNumSent.setVisible(false);
    }

    public void visualizzaAsterisco1(boolean stato) {
        this.jAsteriscoNotReato.setVisible(stato);
    }
    
    public void visualizzaAsterisco2(boolean stato) {
        this.jAsteriscoRGNR.setVisible(stato);
    }

    public void visualizzaAsterisco3(boolean stato) {
        this.jAsteriscoRGGIP.setVisible(stato);
    }

    public void visualizzaAsterisco4(boolean stato) {
        this.jAsteriscoNumSent.setVisible(stato);
    }

    public void abilitaErroreGenerico(boolean stato) {
        this.jLabel1.setText("Attenzione controlla i campi con *");
        this.jLabel1.setVisible(stato);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAsteriscoNotReato;
    private javax.swing.JLabel jAsteriscoNumSent;
    private javax.swing.JLabel jAsteriscoRGGIP;
    private javax.swing.JLabel jAsteriscoRGNR;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlClienteSelezionato;
    private javax.swing.JTextField txNotReato;
    private javax.swing.JTextField txNumSentenza;
    private javax.swing.JTextField txRGGIP;
    private javax.swing.JTextField txRGNR;
    // End of variables declaration//GEN-END:variables

}
