/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinestraNuovoCliente.java
 *
 * Created on 9-gen-2012, 17.14.29
 */

package gestionale.view;

import gestionale.Constants;
import gestionale.control.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 *
 * @author nicolafelicecapece
 */
public class FinestraNuovoCliente extends javax.swing.JDialog {

    private Vista vista;
    private boolean stato;
    private WindowAdapter ad;
    private List<JLabel> listaLabel = new ArrayList<JLabel>();
    private Log logger = LogFactory.getLog(this.getClass());

    /** Creates new form FinestraNuovoCliente */
    public FinestraNuovoCliente(Vista vista) {
        this.vista = vista;
        initComponents();
        postInizializza();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lbCognome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCodice = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        txProvinciaNascita = new javax.swing.JTextField();
        txRecapito = new javax.swing.JTextField();
        txReato = new javax.swing.JTextField();
        txNumTel = new javax.swing.JTextField();
        txNumCell = new javax.swing.JTextField();
        txCodFisc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txNotReato = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txRGNR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jlStatoFascicolo = new javax.swing.JLabel();
        jasterisco1 = new javax.swing.JLabel();
        jasterisco2 = new javax.swing.JLabel();
        jasterisco3 = new javax.swing.JLabel();
        jasterisco4 = new javax.swing.JLabel();
        jasterisco5 = new javax.swing.JLabel();
        jasterisco7 = new javax.swing.JLabel();
        jasterisco6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jasterisco8 = new javax.swing.JLabel();
        jasterisco9 = new javax.swing.JLabel();
        jasterisco10 = new javax.swing.JLabel();
        jasterisco11 = new javax.swing.JLabel();
        lbLuogoNascita = new javax.swing.JLabel();
        jAsterisco13 = new javax.swing.JLabel();
        txCognome = new javax.swing.JTextField();
        txLuogoNascita = new javax.swing.JTextField();
        jAsterisco12 = new javax.swing.JLabel();
        lbProvNascita = new javax.swing.JLabel();
        lbDataNascita = new javax.swing.JLabel();
        jDataNascita = new com.toedter.calendar.JDateChooser();
        txRGGIP = new javax.swing.JTextField();
        txNumSentenza = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        lbCognome.setText("Cognome");

        jLabel3.setText("Recapito");

        jLabel4.setText("Reato");

        jLabel5.setText("Num. Tel.");

        jLabel6.setText("Num. Cell.");

        lbCodice.setText("Codice Fiscale");

        txNumTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumTelActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ente");

        jLabel7.setText("Privato");

        jLabel8.setText("Notizia di reato");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        jLabel9.setText("RGNR");

        jLabel10.setText("RG-GIP");

        jLabel11.setText("Numero Sentenza");

        jLabel12.setText("jLabel12");

        jlStatoFascicolo.setForeground(new java.awt.Color(255, 0, 0));

        jasterisco1.setBackground(new java.awt.Color(255, 0, 0));
        jasterisco1.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco1.setText("    *");

        jasterisco2.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco2.setText("    *");

        jasterisco3.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco3.setText("   *");

        jasterisco4.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco4.setText("    *");

        jasterisco5.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco5.setText("    *");

        jasterisco7.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco7.setText("   *");

        jasterisco6.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco6.setText("    *");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Attenzione i campi con * vanno verificati");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));

        jasterisco8.setBackground(new java.awt.Color(255, 0, 0));
        jasterisco8.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco8.setText("   *");

        jasterisco9.setBackground(new java.awt.Color(255, 0, 0));
        jasterisco9.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco9.setText("   *");

        jasterisco10.setBackground(new java.awt.Color(255, 0, 0));
        jasterisco10.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco10.setText("   *");

        jasterisco11.setBackground(new java.awt.Color(255, 0, 0));
        jasterisco11.setForeground(new java.awt.Color(255, 0, 0));
        jasterisco11.setText("   *");

        lbLuogoNascita.setText("Luogo di Nascita");

        jAsterisco13.setForeground(new java.awt.Color(255, 0, 0));
        jAsterisco13.setText(" *");

        jAsterisco12.setForeground(new java.awt.Color(255, 0, 0));
        jAsterisco12.setText("  *");

        lbProvNascita.setText("Provincia di Nascita (es. PZ)");

        lbDataNascita.setText("Data Nascita");

        jButton3.setText("jButton3");

        jLabel15.setText("Sesso");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lbCodice)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jRadioButton1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel2))
                                    .add(jLabel1)
                                    .add(lbCognome)
                                    .add(jLabel3)
                                    .add(jLabel4)
                                    .add(jLabel5)
                                    .add(jLabel6))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 62, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                    .add(jasterisco5)
                                                    .add(jasterisco6)
                                                    .add(jasterisco4)
                                                    .add(jasterisco7))
                                                .add(8, 8, 8))
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jasterisco1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(layout.createSequentialGroup()
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                            .add(jasterisco3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                            .add(jasterisco2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                                                        .add(3, 3, 3)))
                                                .add(2, 2, 2))))
                                    .add(layout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(jRadioButton2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel7)))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txRecapito, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(txReato, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(txNumTel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(txNumCell, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(txCodFisc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txCognome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(77, 77, 77)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lbDataNascita)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                            .add(lbLuogoNascita)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jAsterisco12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, lbProvNascita))
                                    .add(jLabel15)))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                    .add(layout.createSequentialGroup()
                                                        .add(3, 3, 3)
                                                        .add(jlStatoFascicolo)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 82, Short.MAX_VALUE))
                                                    .add(jAsterisco13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(txProvinciaNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, txLuogoNascita)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jDataNascita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .add(18, 18, 18))
                                    .add(layout.createSequentialGroup()
                                        .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jLabel8)
                                                .add(jLabel9)
                                                .add(jLabel10)
                                                .add(jLabel12))
                                            .add(18, 18, 18)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                    .add(jasterisco8)
                                                    .add(jasterisco10))
                                                .add(jasterisco9))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(txNotReato)
                                                .add(txRGNR, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                                .add(txRGGIP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel11)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jasterisco11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(2, 2, 2)
                                            .add(txNumSentenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(37, 37, 37))
                            .add(layout.createSequentialGroup()
                                .add(75, 75, 75)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel14)
                                    .add(jLabel13))))
                        .add(86, 86, 86))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .add(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jRadioButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jRadioButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .add(18, 18, 18))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel12)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel1)
                        .add(lbLuogoNascita)
                        .add(txNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jasterisco1))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(jasterisco9)
                        .add(txNotReato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(txLuogoNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jAsterisco12)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbCognome)
                            .add(txCognome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbProvNascita)
                            .add(jLabel9)
                            .add(txProvinciaNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jAsterisco13)
                            .add(jasterisco2)))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txRGNR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco8))))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(txRecapito, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco3))
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(txReato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco4)
                            .add(jLabel15)
                            .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(txNumTel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco5))
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(txNumCell, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco6)
                            .add(jButton2)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(lbDataNascita)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jDataNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel10)
                                    .add(txRGGIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jasterisco10))))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txNumSentenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jasterisco11))
                        .add(26, 26, 26)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(203, 203, 203)
                        .add(jlStatoFascicolo)))
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbCodice)
                    .add(txCodFisc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jasterisco7)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel14)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jLabel13))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txNumTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumTelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jAsterisco12;
    private javax.swing.JLabel jAsterisco13;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDataNascita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jasterisco1;
    private javax.swing.JLabel jasterisco10;
    private javax.swing.JLabel jasterisco11;
    private javax.swing.JLabel jasterisco2;
    private javax.swing.JLabel jasterisco3;
    private javax.swing.JLabel jasterisco4;
    private javax.swing.JLabel jasterisco5;
    private javax.swing.JLabel jasterisco6;
    private javax.swing.JLabel jasterisco7;
    private javax.swing.JLabel jasterisco8;
    private javax.swing.JLabel jasterisco9;
    private javax.swing.JLabel jlStatoFascicolo;
    private javax.swing.JLabel lbCodice;
    private javax.swing.JLabel lbCognome;
    private javax.swing.JLabel lbDataNascita;
    private javax.swing.JLabel lbLuogoNascita;
    private javax.swing.JLabel lbProvNascita;
    private javax.swing.JTextField txCodFisc;
    private javax.swing.JTextField txCognome;
    private javax.swing.JTextField txLuogoNascita;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNotReato;
    private javax.swing.JTextField txNumCell;
    private javax.swing.JTextField txNumSentenza;
    private javax.swing.JTextField txNumTel;
    private javax.swing.JTextField txProvinciaNascita;
    private javax.swing.JTextField txRGGIP;
    private javax.swing.JTextField txRGNR;
    private javax.swing.JTextField txReato;
    private javax.swing.JTextField txRecapito;
    // End of variables declaration//GEN-END:variables

    private void postInizializza() {
       this.setModal(true);
       controlloErrori();
       creaListaLabel();
       this.buttonGroup1.add(jRadioButton1);
       this.buttonGroup1.add(jRadioButton2);
       this.jRadioButton1.setSelected(true);

       AzioneInfo ai = (AzioneInfo) this.vista.getControllo().getAzione(Constants.AZIONE_INFO);
       this.jMenuItem4.setAction(ai);
       AzioneNuovoCliente anc = (AzioneNuovoCliente) this.vista.getControllo().getAzione(Constants.AZIONE_NUOVO_CLIENTE);
       this.jButton1.setAction(anc);
       AzioneJRadioButton ajrb = (AzioneJRadioButton) this.vista.getControllo().getAzione(Constants.AZIONE_JRADIO_BUTTON);
       this.jRadioButton1.setAction(ajrb);
       this.jRadioButton2.setAction(ajrb);
       AzioneAggiungiFascicolo aac = (AzioneAggiungiFascicolo) this.vista.getControllo().getAzione(Constants.AZIONE_AGGIUNGI_FASCICOLO);
       this.jButton2.setAction(aac);
       ModelloComboBoxAutGiud mcbag = new ModelloComboBoxAutGiud();
       this.jComboBox1.setModel(mcbag);
       this.jComboBox1.setSelectedIndex(0);
       AzioneSalva as = (AzioneSalva) this.vista.getControllo().getAzione(Constants.AZIONE_SALVA);
       this.jMenuItem1.setAction(as);
       AzioneIndietroFinestraAC afac = (AzioneIndietroFinestraAC) this.vista.getControllo().getAzione(Constants.AZIONE_INDIETRO_AC);
       this.jMenuItem2.setAction(afac);
       AzioneEsci ae = (AzioneEsci) this.vista.getControllo().getAzione(Constants.AZIONE_ESCI);
       this.jMenuItem3.setAction(ae);
       this.jLabel12.setText("");

       ModelloComboBoxSesso mcbs = new ModelloComboBoxSesso();
       this.jComboBox2.setModel(mcbs);
       this.jComboBox2.setSelectedIndex(0);
       AzioneCodiceFiscale acf = (AzioneCodiceFiscale) this.vista.getControllo().getAzione(Constants.AZIONE_CODICE_FISCALE);
       this.jButton3.setAction(acf);
        //this.addMouseListener(new PopClickListener(this.vista));
      
       abilitaFascicolo(false);
       aggiustaLabel();
    }

    public void riempiLabelRiepilogo(String dati) {
        this.jLabel12.setText(dati);
    }

    public void riempiLabelStatoFascicolo(String stringa) {
        this.jlStatoFascicolo.setText("Il fascicolo: " + stringa + " e' stato inserito");
    }

    public void riempiCodFisc(String text) {
        this.txCodFisc.setText(text);
    }

    public void aggiustaLabel() {
       if (this.selezionaTipo() == 1) {
           this.lbCognome.setEnabled(false);
           this.txCognome.setEnabled(false);
           this.lbLuogoNascita.setEnabled(false);
           this.txLuogoNascita.setEnabled(false);
           this.lbProvNascita.setEnabled(false);
           this.txProvinciaNascita.setEnabled(false);
           this.lbDataNascita.setEnabled(false);
           this.jDataNascita.setEnabled(false);
           this.jLabel15.setEnabled(false);
           this.jComboBox2.setEnabled(false);
           this.jButton3.setEnabled(false);
           this.lbCodice.setText("Partita IVA");
           this.repaint();
       } else {
           this.lbCognome.setEnabled(true);
           this.txCognome.setEnabled(true);
           this.lbLuogoNascita.setEnabled(true);
           this.txLuogoNascita.setEnabled(true);
           this.lbProvNascita.setEnabled(true);
           this.txProvinciaNascita.setEnabled(true);
           this.lbDataNascita.setEnabled(true);
           this.jDataNascita.setEnabled(true);
           this.jLabel15.setEnabled(true);
           this.jComboBox2.setEnabled(true);
           this.jButton3.setEnabled(true);
           this.lbCodice.setText("Codice FIS");
           this.repaint();
       }
    }

    public String getSesso() {
        return (String) this.jComboBox2.getSelectedItem();
    }

    public String restituisciNome() {
        return this.txNome.getText();
    }

    public String restituisciCognome() {
        return this.txCognome.getText();
    }

    public String restituisciNumTel() {
        return this.txNumTel.getText();
    }

    public String restituisciNumCell() {
        return this.txNumCell.getText();
    }

    public String restituisciReato() {
        return this.txReato.getText();
    }

    public String restituisciRecapito() {
        return this.txRecapito.getText();
    }

    public String restituisciDatoAstratto() {
        return this.txCodFisc.getText();
    }

    public void visualizzati(boolean stato) {
        this.setVisible(stato);
    }

    public String restituisciAutGiud() {
        return (String) this.jComboBox1.getSelectedItem();
    }

    public String restituisciNotReato() {
        return this.txNotReato.getText();
    }

    public String restituisciRGGIP() {
        return this.txRGGIP.getText();
    }

    public String restituisciRGNR() {
        return this.txRGNR.getText();
    }

    public String restituisciNumSentenza() {
        return this.txNumSentenza.getText();
    }

    public String restituisciLuogoNascita() {
        return this.txLuogoNascita.getText();
    }

    public String restituisciProvNascita() {
        return this.txProvinciaNascita.getText();
    }

    public Calendar restituisciDataNascita() {
        return this.jDataNascita.getCalendar();
    }

    public int selezionaTipo() {
        if (jRadioButton1.isSelected()) {
            return 1;
        } else if (jRadioButton2.isSelected()) {
            return 2;
        } else {
            return 0;
        }
    }


    public void controllaStatoSalvataggio() {
       final AzioneSalva as = (AzioneSalva) this.vista.getControllo().getAzione(Constants.AZIONE_SALVA);
       ad = new WindowAdapter() {
       @Override
            public void windowClosing(WindowEvent e) {
                int reply = JOptionPane.showConfirmDialog(vista, "Attenzione stai uscendo senza salvare... Vuoi salvare adesso ?", "Informazione", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (reply == JOptionPane.YES_OPTION) {
                    as.actionPerformed(null);
                    JOptionPane.showMessageDialog(vista, "Salvataggio effettuato", "Informazione", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    rimuoviListner();
                }
            }
        };
        this.addWindowListener(ad);
    }

    public void controllaSeSalvato() {
        if (this.isStato()) {
            this.removeWindowListener(ad);
        } 
    }

    public void rimuoviListner() {
        this.removeWindowListener(ad);
    }
    

    public void disabilitaInserimento(boolean stato) {
        this.jLabel1.setEnabled(stato);
        this.jLabel2.setEnabled(stato);
        this.jLabel3.setEnabled(stato);
        this.jLabel4.setEnabled(stato);
        this.jLabel5.setEnabled(stato);
        this.jLabel6.setEnabled(stato);
        this.jLabel7.setEnabled(stato);
        this.lbLuogoNascita.setEnabled(stato);
        this.lbProvNascita.setEnabled(stato);
        this.lbDataNascita.setEnabled(stato);
        this.lbCodice.setEnabled(stato);
        this.lbCognome.setEnabled(stato);
        this.jLabel15.setEnabled(stato);
        this.txCodFisc.setEnabled(stato);
        this.txCognome.setEnabled(stato);
        this.txNome.setEnabled(stato);
        this.txNumCell.setEnabled(stato);
        this.txNumTel.setEnabled(stato);
        this.txReato.setEnabled(stato);
        this.txRecapito.setEnabled(stato);
        this.txLuogoNascita.setEnabled(stato);
        this.txProvinciaNascita.setEnabled(stato);
        this.jDataNascita.setEnabled(stato);
        this.jRadioButton1.setEnabled(stato);
        this.jRadioButton2.setEnabled(stato);
        this.jButton1.setEnabled(stato);
        this.jButton3.setEnabled(stato);
        this.jComboBox2.setEnabled(stato);
    }

    public void abilitaFascicolo(boolean stato) {
        this.jLabel8.setEnabled(stato);
        this.jLabel9.setEnabled(stato);
        this.jLabel10.setEnabled(stato);
        this.jLabel11.setEnabled(stato);
        this.jComboBox1.setEnabled(stato);
        this.txNotReato.setEnabled(stato);
        this.txNumSentenza.setEnabled(stato);
        this.txRGGIP.setEnabled(stato);
        this.txRGNR.setEnabled(stato);
        this.jButton2.setEnabled(stato);
    }

    public void pulisciCampi() {
        this.txCodFisc.setText("");
        this.txCognome.setText("");
        this.txNome.setText("");
        this.txNumCell.setText("");
        this.txNotReato.setText("");
        this.txNumSentenza.setText("");
        this.txRGGIP.setText("");
        this.txRGNR.setText("");
        this.txNumTel.setText("");
        this.txReato.setText("");
        this.txRecapito.setText("");
    }

    /**
     * @return the stato
     */
    public boolean isStato() {
        return stato;
    }

    /**
     * @param stato the stato to set
     */
    public void setStato(boolean stato) {
        this.stato = stato;
    }

    public void controlloErrori() {
        for(JLabel jl : listaLabel) {
            jl.setVisible(false);
        }
    }

    //Errore Utente

    public void abilitaAsterischi(boolean stato, String nome) {
        for(JLabel jl : listaLabel) {
            //logger.info("Nome label: " + jl.getName());
            if (jl.getName().equals(nome)) {
                jl.setVisible(stato);
            }
        }
    }

    public void abilitaErroreGenerico(boolean stato) {
        this.jLabel13.setVisible(stato);
    }

    public void riempiLabel(String text) {
        this.jLabel14.setText(text);
    }

    private void creaListaLabel() {
        jasterisco1.setName("nome");
        listaLabel.add(jasterisco1);

        jasterisco2.setName("cognome");
        listaLabel.add(jasterisco2);

        jasterisco3.setName("recapito");
        listaLabel.add(jasterisco3);

        jasterisco4.setName("reato");
        listaLabel.add(jasterisco4);

        jasterisco5.setName("numTel");
        listaLabel.add(jasterisco5);

        jasterisco6.setName("numCell");
        listaLabel.add(jasterisco6);

        jasterisco7.setName("datoAstratto");
        listaLabel.add(jasterisco7);

        jasterisco8.setName("notReato");
        listaLabel.add(jasterisco8);

        jasterisco9.setName("rgnr");
        listaLabel.add(jasterisco9);

        jasterisco10.setName("rg-gip");
        listaLabel.add(jasterisco10);

        jasterisco11.setName("numSent");
        listaLabel.add(jasterisco11);

        jAsterisco12.setName("luogoNascita");
        listaLabel.add(jAsterisco12);

        jAsterisco13.setName("provNascita");
        listaLabel.add(jAsterisco13);
    }

    public void modificaRadioButton() {
       //Impostare il jRadioButton evidenziato in blue
        this.jRadioButton1.setSelected(true);
        this.jasterisco2.setEnabled(false);
        this.lbCognome.setEnabled(false);
        this.txCognome.setEnabled(false);
    }
}
