/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PannelloPrincipale1.java
 *
 * Created on 20-mag-2012, 23.43.29
 */

package gestionale.view;

import gestionale.Constants;
import gestionale.control.AzioneAggiungiCliente;
import gestionale.control.AzioneCercaCliente;
import gestionale.control.AzioneRimuovi;
import gestionale.control.AzioneSelezionaCliente;
import gestionale.model.Gestionale;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author nicolafelicecapece
 */
public class PannelloPrincipale extends javax.swing.JPanel {
    
    private Vista vista;
    //private Log logger = LogFactory.getLog(this.getClass());

    /** Creates new form PannelloPrincipale */
    public PannelloPrincipale(Vista vista) {
        this.vista = vista;
        initComponents();
        postInizializza();
    }

    private void postInizializza() {
        this.vista.setInizializzaStato(1);
        AzioneCercaCliente accli = (AzioneCercaCliente) this.vista.getControllo().getAzione(Constants.AZIONE_CERCA_CLIENTE);
        this.jButton1.setAction(accli);

        AzioneAggiungiCliente aac = (AzioneAggiungiCliente) this.vista.getControllo().getAzione(Constants.AZIONE_AGGIUNGI_CLIENTE);
        this.jButton2.setAction(aac);
        AzioneRimuovi ar = (AzioneRimuovi) this.vista.getControllo().getAzione(Constants.AZIONE_RIMUOVI);
        this.jButton3.setAction(ar);
        final AzioneSelezionaCliente asc = (AzioneSelezionaCliente) this.vista.getControllo().getAzione(Constants.AZIONE_SELEZIONA);
        this.jbSeleziona.setAction(asc);

        this.addMouseListener(new PopClickListener(this.vista));

        this.jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                   asc.actionPerformed(null);
                }
            }
        });

        riempiTabella();

        inserisciIcone();
        this.setVisible(true);
    }

    public void riempiTabella() {
        Gestionale gestionale = (Gestionale) this.vista.getModello().getBean(Constants.GESTIONALE);
        ModelloTabellaClienti mtc = new ModelloTabellaClienti(gestionale);
        this.jTable1.setModel(mtc);
    }

    public String ottieniTesto() {
        return this.jTextField1.getText();
    }

    public int indiceSeleziona() {
        return this.jTable1.getSelectedRow();
    }

    public void pulisciPannello() {
        this.jTextField1.setText("");
    }

    public void disablitaTutto() {
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jbSeleziona.setEnabled(false);
        this.jTable1.setEnabled(false);
        this.jTextField1.setEnabled(false);
    //  this.jLabel2.setEnabled(false);
    }
    private void inserisciIcone() {
        String nomeOs = System.getProperty("os.name");
        if (nomeOs.equalsIgnoreCase("windows")){
            this.jButton2.setIcon(new ImageIcon("varie\\risorse\\modelloimmagineadd.png"));
            this.jButton3.setIcon(new ImageIcon("varie\\risorse\\modelloimmagineremove.png"));
        } else {
            this.jButton2.setIcon(new ImageIcon("varie//risorse//modelloimmagineadd.png"));
            this.jButton3.setIcon(new ImageIcon("varie//risorse//modelloimmagineremove.png"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbSeleziona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.setRequestFocusEnabled(false);
        jButton2.setSize(new java.awt.Dimension(60, 60));

        jButton3.setText("jButton3");
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbSeleziona.setText("jButton3");
        jbSeleziona.setPreferredSize(new java.awt.Dimension(100, 50));
        jbSeleziona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelezionaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jbSeleziona, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbSeleziona, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(1, 1, 1)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 513, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jbSelezionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelezionaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbSelezionaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbSeleziona;
    // End of variables declaration//GEN-END:variables


}
