/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PannelloFascicoli.java
 *
 * Created on 27-nov-2011, 18.43.42
 */

package gestionale.view;

import gestionale.Constants;
import gestionale.control.AzioneAggiungiFascicoloClienteEsistente;
import gestionale.control.AzioneIndietro;
import gestionale.control.AzioneRimuoviFascicolo;
import gestionale.control.AzioneVisualizzaUdienze;
import gestionale.model.ClienteAstratto;
import gestionale.model.Privato;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Nicola
 */
public class PannelloFascicoli extends javax.swing.JPanel {

    private Vista vista;

    /** Creates new form PannelloFascicoli */
    public PannelloFascicoli(Vista vista) {
        this.vista = vista;
        initComponents();
        PostInizializza();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCognome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelRecapito = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelReato = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelCellulare = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Nome:");

        labelNome.setText("jLabel2");

        jLabel2.setText("Cognome:");

        labelCognome.setText("jLabel3");

        jLabel3.setText("Recapito:");

        labelRecapito.setText("jLabel4");

        jLabel4.setText("Reato:");

        labelReato.setText("jLabel5");

        jLabel5.setText("Cellulare:");

        labelCellulare.setText("jLabel6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(labelNome)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCognome)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRecapito)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelReato)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCellulare))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(labelRecapito)
                    .addComponent(jLabel4)
                    .addComponent(labelReato)
                    .addComponent(jLabel5)
                    .addComponent(labelCellulare)
                    .addComponent(labelNome)
                    .addComponent(labelCognome))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCellulare;
    private javax.swing.JLabel labelCognome;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelReato;
    private javax.swing.JLabel labelRecapito;
    // End of variables declaration//GEN-END:variables

    private void PostInizializza() {
        AzioneIndietro ai = (AzioneIndietro) this.vista.getControllo().getAzione(Constants.AZIONE_INDIETRO);
        this.jButton2.setAction(ai);
        final AzioneVisualizzaUdienze avc = (AzioneVisualizzaUdienze) this.vista.getControllo().getAzione(Constants.AZIONE_VISUALIZZA_UDIENZE);
        this.jButton1.setAction(avc);
        this.jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    avc.actionPerformed(null);
                }
            }
        });
        AzioneAggiungiFascicoloClienteEsistente aafce = (AzioneAggiungiFascicoloClienteEsistente) this.vista.getControllo().getAzione(Constants.AZIONE_AGGIUNGI_FASCICOLO_CLIENTE_ESISTENTE);
        this.jButton3.setAction(aafce);
        AzioneRimuoviFascicolo arf = (AzioneRimuoviFascicolo) this.vista.getControllo().getAzione(Constants.AZIONE_RIMUOVI_FASCICOLO);
        this.jButton4.setAction(arf);
        this.setVisible(true);
    }

    public void visualizzaDati() {
        ClienteAstratto cliente = (ClienteAstratto) this.vista.getModello().getBean(Constants.CLIENTE);
        riempiTabella();
        this.labelNome.setText(cliente.getNome());
        if (cliente instanceof Privato) {
            Privato privato = (Privato) cliente;
            this.labelCognome.setText(privato.getCognome());
        } else {
            this.labelCognome.setText("");
            this.jLabel2.setText("");
        }
        this.labelCellulare.setText(cliente.getCellulare());
        this.labelReato.setText(cliente.getReato());
        this.labelRecapito.setText(cliente.getRecapito());
    }

    public void riempiTabella() {
        ClienteAstratto cliente = (ClienteAstratto) this.vista.getModello().getBean(Constants.CLIENTE);
        ModelloTabellaFascicoli mtf = new ModelloTabellaFascicoli(cliente);
        this.jTable1.setModel(mtf);
    }

    public int indiceSeleziona() {
        return this.jTable1.getSelectedRow();
    }

}
